version: '3.3'
services:
  postgres:
   image: postgres:13
   environment:
    - POSTGRES_DB=insurances_manager
    - POSTGRES_USER=mrivas
    - POSTGRES_PASSWORD=123
   ports:
    - 5432:5432
   volumes:
    - ./data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=mrivas@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    
